

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 
    displayName: "maven-pacakege"
    jobs:
      - job: pacakge
        steps:
        - task: Maven@4
          inputs:
            azureSubscription: 'Azure subscription 1(2b991cbf-3249-4aa2-9d38-9b026b171757)'
            mavenPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
      


