trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self

- task: Maven@4
  displayName: 'Build Spring Boot JAR'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    options: '-DskipTests'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'

- task: CopyFiles@2
  displayName: 'Copy WAR'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/target'
    Contents: '*.war'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'