trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:

- task: Maven@4
  displayName: 'Build JAR (Skip Tests)'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    options: '-DskipTests'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'

- script: |
    echo ===== Current Directory =====
    cd
    echo ===== Repository Files =====
    dir "$(Build.SourcesDirectory)"
    echo ===== Target Folder =====
    dir "$(Build.SourcesDirectory)\target"
  displayName: 'Verify Build Output'

- task: CopyFiles@2
  displayName: 'Copy JAR'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\target'
    Contents: '*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- script: |
    echo ===== Artifact Staging =====
    dir "$(Build.ArtifactStagingDirectory)"
  displayName: 'Verify Artifact'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'


